
namespaceOverride: "monitoring"


alertmanager:
  ingress:
    enabled: true
    hosts:
      - monitor.test
    path: /alertmanager

  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 3Gi

grafana:
  adminPassword: gra@07@5A_@
 
  ingress:
    enabled: true
    hosts:
      - monitor.test
    path: /

  persistence:
    type: pvc
    enabled: true
    #storageClassName: gp2
    accessModes: ["ReadWriteOnce"]
    size: 5Gi

prometheus:
  ingress:
    enabled: true
    hosts:
      - monitor.test
    path: /prometheus

  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
